language: php

php:
  # - '5.6'
  - '7.0'
  # - '7.1'

sudo: false

before_script:
  - cp .env.ci .env
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
#  - php artisan migrate --seed

script:
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - gtaylor@electricwerks.com
    on_success: always
    on_failure: always
